### ISSUE TITLE
Null pointer in RendererAdapter

### ISSUE THREAD

**Issue by matt1as** [Alexrs95/RecyclerViewRenderers#3]
When trying to create a Recyclerview in a Fragment I get the following null pointer exception. I'm sure I have missed something, but the documentation/example were using an activity, and I'm trying to do it from a Fragment, so I could not reuse everything from the example.

```
04-12 23:08:09.370    9172-9172/se.speedle.android E/AndroidRuntime﹕ FATAL EXCEPTION: main
java.lang.NullPointerException
        at me.alexrs.recyclerviewrenderers.adapter.RendererAdapter.onCreateViewHolder(RendererAdapter.java:66)
        at me.alexrs.recyclerviewrenderers.adapter.RendererAdapter.onCreateViewHolder(RendererAdapter.java:35)
        at android.support.v7.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:4121)
        at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:3431)
        at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:3340)
        at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:1810)
        at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1306)
        at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1269)
        at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:523)
        at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:1988)
        at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:2237)
        at android.view.View.layout(View.java:14289)
        at android.view.ViewGroup.layout(ViewGroup.java:4562)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
        at android.view.View.layout(View.java:14289)
        at android.view.ViewGroup.layout(ViewGroup.java:4562)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
        at android.view.View.layout(View.java:14289)
        at android.view.ViewGroup.layout(ViewGroup.java:4562)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
        at android.view.View.layout(View.java:14289)
        at android.view.ViewGroup.layout(ViewGroup.java:4562)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1671)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1525)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1434)
        at android.view.View.layout(View.java:14289)
        at android.view.ViewGroup.layout(ViewGroup.java:4562)
        at android.support.v4.widget.DrawerLayout.onLayout(DrawerLayout.java:890)
        at android.view.View.layout(View.java:14289)
        at android.view.ViewGroup.layout(ViewGroup.java:4562)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
        at android.view.View.layout(View.java:14289)
        at android.view.ViewGroup.layout(ViewGroup.java:4562)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1671)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1525)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1434)
        at android.view.View.layout(View.java:14289)
        at android.view.ViewGroup.layout(ViewGroup.java:4562)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
        at android.view.View.layout(View.java:14289)
        at android.view.ViewGroup.layout(ViewGroup.java:4562)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1671)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1525)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1434)
        at android.view.View.layout(View.java:14289)
        at android.view.ViewGroup.layout(ViewGroup.java:4562)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
        at android.view.View.layout(View.java:14289)
        at android.view.ViewGroup.layout(ViewGroup.java:4562)
        at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:1976)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1730)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1004)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5481)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:749)
        at android.view.Choreographer.doCallbacks(Choreographer.java:562)
        at android.view.Choreographer.doFrame(Choreographer.java:532)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:735)
        at android.os.Handler.handleCallback(Handler.java:730)
        at android.os.Handler.dispatchMessage(Handler.java:92)
        at android.os.Looper.loop(Looper.java:137)
        at android.app.ActivityThread.main(ActivityThread.java:5103)
        at java.lang.refle
```

My code is available at https://github.com/matt1as/speedleandroid2 and i think the offending code is in https://github.com/matt1as/speedleandroid2/blob/master/src/main/java/com/bryderi/speedle/android/fragments/DashboardFragment.java

Thanks in advance

**Comment by alexrs** [comment]
Hi Mattias,

I have found the error in your code! As you have noticed, the classes that contains the data you want to display must implement `Renderable`. In your case, you want to show the data contained in `Classified`, and you have implemented `Renderable` in that class, the method `getRenderableId` must return the layout you will show in the `RecyclerView`. Everything okay until here. Now, this layout is used in the `Factory` to select the `Renderer`. Change this in your Factory and your code will work:

``` JAVA
case R.layout.fragment_splash:
         return new ClassifiedRenderer(id);
```

for this

``` JAVA
case R.layout.classified:
         return new ClassifiedRenderer(id);
```

I have also found another bug related with your layout. You can not use `android:layout_weight` with a `RelativeLayout`. Fix this in `classified.xml`.

**Comment by matt1as** [comment]
Hello,

Great,thanks,now everything is working.

Regards 
Mattias 

Skickat från min iPhone
